export default{
    threePointsBtnXpath:'//div[@id="main"]//ul/li/a[@id="nav-users-tab"]//ancestor::div[@id="mainbody"]/descendant::div[@class="container-fluid"]//table/tbody/tr//button[@aria-haspopup="menu"]',
    searchInputBox:"[id='search'] input",
    searchctrl:"//i[@class='fas fa-search']",
    RecordBtnForGivenCollection:" //span[text()[normalize-space()='collectionName']]//ancestor::tr//a[@title='Records']",
    RecordsBtn: '[title="Records"]',
    collectionNameInput:"//span[text()='collectionName']",
    newCollectionBtn:'[aria-label="Create Collection"]',
    nameInputTxtBx:'[id="name"]',
    descriptionInputTxtBx:'[id="description"]',
    createscreenForInputDropdown: '//label[normalize-space(text())="Create Screen"]//following-sibling::div/div',
    createscreenInputTxtBx: '[name="create_screen_id"]',
    screenDropdownOption: '//li[@role="option"]//span[text()="screenName"]',
    viewScreenForInputDropdown:"//label[normalize-space(text())='View Screen']//following-sibling::div/div",
    viewScreenInputTxtBx: '[name="read_screen_id"]',
    editScreenForInputDropdown:"//label[normalize-space(text())='Edit Screen']//following-sibling::div/div",
    editScreenInputTxtBx: '[name="update_screen_id"]',
    collectionsaveBtn:"//button[text()='Save']",
    newRecordBtn:'[id="addUserCollection"]',
    dateinputTxtBx:'//input[@name="releaseDate"]',
    titleInputTxtBx:'[name="title"]',
    authorInputTxtBx:'[name="author"]',
    priceInputTxtBx:'[name="price"]',
    submitBtn:'[class="btn btn-primary"]',
    navEditBtn:'[id="nav-edit-record-tab"]',
    //collectionNameInput:'//a[text()[normalize-space()="name"]]',

    //users
    newUserBtn: 'button[aria-label="Create User"]',
    usernameInputTxtBox: '[id="username"]',
    firstNameInputTxtBox: '[id="firstname"]',
    lastNameInputTxtBox: '[id="lastname"]',
    jobTitleInputTxtBox: '[id="title"]',
    statusDropdown: '[id="status"]',
    emailInputTxtBox: '[id="email"]',
    passwordInputTxtBox: '[id="password"]',
    confirmPasswordInputTxtBox: '[id="confpassword"]',
    saveUserBtn: '[id="saveUser"]',
    profileUserLabel: '//h5[text()="Profile"]',
    searchUserField: "(//input[@id='search-box'])[1]",
    searchButton: "(//button[@aria-label='Search'])[1]",
    selectListLanguage: "//select[@id='language']",
    tabPermissions: "div[id='nav-tab'] > a[id='nav-profile-tab']",
    tabInformation: "div[id='nav-tab'] > a[id='nav-home-tab']",
    switchChangePassword: "(//input[@id='switch_force_change_password'])[1]",
    editUserButton: '//span[text()="Edit User"]',

    //DeleteUser
    tableUsers:'div > table',
    deleteTitleModal: 'h5[class="modal-title"]',
    cancelDeleteUserBtn: 'btn m-0 btn-outline-secondary',
    confirmDeleteUserBtn: '[class="btn m-0 btn-secondary"]',
    redAlertMessage:'div[class="alert-wrapper"] > div',

    //groups
    newGroupBtn: '.d-flex > .btn',
    nameGroupInputTxtBox: '[id="name"]',
    descriptionGroupTextareaBox: '[id="description"]',
    saveGroupBtn: '//button[text()[normalize-space()="Save"]]',
    groupDetailsTab: '[id = "nav-home-tab"]',
    userTab: '//a[text()="Users"]',
    newUserToGroupBtn: '#nav-users > #search-bar > :nth-child(1) > .d-flex > .btn',
    usersInputTxtBox: 'input[id = "users"]',
    saveUserToGroupBtn: '#addUser___BV_modal_footer_ > .btn-secondary',

    groupTab: '//a[text()="Group Permissions"]',
    permissionProcessTab: '//div[text()="Processes"]',
        createProcessPermissionLabel: '//label[text()="Create Processes"]',
        editProcessPermissionLabel: '//label[text()="Edit Processes"]',
        viewProcessPermissionLabel: '//label[text()="View Processes"]',
    savePermissionGroupBtn: '[id = "savePermissions"]',


    configBtn:'//a[@class="btn btn-outline-secondary"]//i[1]',
    createSignalBtn:'[for="signal_create"]',
    updateSignalBtn:'[for="signal_update"]',
    deleteSignalBtn:'[for="signal_delete"]',
    collectionSaveBtnSignl:"(//button[text()='Save'])[1]",
    studentDateInputTxtBx:'(//*[@type="text"])[1]',
    CIInputTxt:'[name="CI"]',
    studentNameInputTxtBx:'[name="name"]',
    lastNameInputTxtBx:'[name="lastName"]',
    selectlistBtn:'[class="multiselect__tags"]',
    selectOption:"(//li[@class='multiselect__element']//span)[1]",
    phoneNumberInputTxtBx:'[data-cy="screen-field-telephone"]',
    userInputTxtBx:'(//*[@placeholder="Search"])[1]',
    userTxt:'//td//span[text()[normalize-space()="userName"]]',
    userIdInput:'(//td//span[text()[normalize-space()="userName"]]//parent::td//preceding-sibling::td)[1]',

    //Sidebar
    expandSidebarMenu:'.nav-item.filter-bar.justify-content-between.py-2.sidebar-expansion',
    optionInSidebar:'.nav-item.filter-bar.justify-content-between',
    //Permission Users
    permissionTabUser:'#nav-profile-tab',
    makeSuperAdmin:'//*[@id="accordionPermissions"]/div[1]',
    makeAdmin:'//*[@id="accordionPermissions"]/div[2]',
    userPermissionSaveButton:'#savePermissions',
    userPermissionMessage: ".alert-wrapper > .alert > span",
    editctrl: "[title='Edit'] > .fas",
    loadingSpinnerCollection: "#collectionIndex > div.container-fluid > div > div.jumbotron.jumbotron-fluid",
    collectionTable: '//div[@id="collectionIndex"]/div[2]/div/div/table/tbody/tr',
    importCollectionBtn: "[id='import_collection']",
    browseBtn: "[id='pre-import']>button",
    inputToFileUpload: "[type='file']",
    importBtn: "button.btn.btn-secondary.ml-2",
    loadingCollectionSpinner: "[class='fas fa-circle-notch fa-spin']",
    //EditGroup
    groupDetailsTableContent: "#nav-home",
    labelHomePage: ' //label[text()="Home Page"]',
    labelDashboard: ' //label[text()="Dashboard"]',
    labelMenu: '//label[text()="Top Menu"]',
    homePageInputInGroup: '[class="multiselect__tags"]',
    divContainerOptionHomePage:
        '//label[text()="Home Page"]/parent::div//div//div[@class="multiselect__tags"]',
    divContainerOptionDashboard:
        '//label[text()="Dashboard"]/parent::div//div//div[@class="multiselect__tags"]',
    divContainerOptionTopMenu:
        '//label[text()="Top Menu"]/parent::div//div//div[@class="multiselect__tags"]',
    inputOptionHomePage:
        '//label[text()="Home Page"]/parent::div//div//div[@class="multiselect__tags"]//input',
    inputOptionDashboard:
        '//label[text()="Dashboard"]/parent::div//input',
    inputOptionTopMenu:
        '//label[text()="Top Menu"]/parent::div//input',
    listOptionHomePage:
        '//ul[@id="listbox-1"]//li//span[text()="My Dashboard"]',
    listOptionDashboard:
        '//ul[@id="listbox-3"]//li//span[text()="dashboardName"]',
    listOptionTopMenu:
        '//ul[@id="listbox-2" ]//li//span//span[text()="menuName"]',
    formGroupInput: '[class="form-group"]',
    saveGroupDetailsBtn: '[id="saveGroup"]',
    //Delete Dashboards and Menus
    rowInDashboardTable:
        '//*[@id="editCss"]/div/div/div/div/div/div[2]/div/table/tbody/tr',
    rowInMenuTable:
        '//*[@id="editCss"]/div/div/div/div/div/div[2]/div/div/table/tbody/tr',
    columnInTable: '[class="vuetable-slot"]',
    deleteBtnInTable: '[class="fas fa-trash-alt fa-lg fa-fw"]',
    confirmDeleteBtn: '[class="btn m-0 btn-secondary"]',

    //Collection
    configCollectionBtn: "//span[text()[normalize-space()='collectionName']]//ancestor::tr//a[@title='Configure']",
    deleteCollectionBtn: "//span[text()[normalize-space()='collectionName']]//ancestor::tr//button[@title='Delete']",
    collectionColumnsTab:"//a[text()='Columns']",
    collection_configButton:"[title='Configure Collection']",
    activeColumns_coulumnLinkDelete: "//span[text()='nameColumn']/parent::div/following-sibling::div/a",
    activeColumns_resetToDefaultBtn: "//text()[contains(.,'Reset to Default')]/ancestor::button[1]",
    activeColumns_addCustomColumnLink: "//div[contains(text(),'Add Custom Column')]/parent::a",
    customColumn_label: "//legend[text()='Label']/parent::fieldset//input",
    customColumn_field: "//legend[text()='Field']/parent::fieldset//input",
    customColumn_save: "//footer//button[contains(text(),'Save')]",
    searchCollection: "//input[@placeholder='Search']",
    collectionTitle: '//input[@id="collectionTitle"]',
    collectionDescription: '//textarea[@id="description"]',
    saveButton: '(//button[text()="Save"])[1]',
    confirXPATH: "//button[text()='Confirm']",

    //group
    clickonGroupBtn: "(//i[contains(@class,'fas nav-icon')])[2]",
    GroupPagevisible: "//li[text()[normalize-space()='Groups']]",
    clickonplsGroup: "//button[text()[normalize-space()='Group']]",
    groupNameBtn: "//input[@class='form-control form-control']",
    descriptionBtn: "//label[text()='Description']/following::textarea",
    groupsaveBtn:"//button[text()='Save']",
    CrtGrpPageVsb: "(//a[@data-toggle='tab'])[1]",
    clickonUserBtn: "//a[@href='#nav-users']",
    userPageVsble: "//button[text()[normalize-space()='User']]",
    crtuserBtn: "//button[text()[normalize-space()='User']]",
    selectUserBtn: "//label[text()='Users']/following::input",
    userInputText:'//span[contains(text(),"testname1")]',
    clickonSaveBtn: "(//button[text()='Save'])[3]",
    clickonGroup: "(//a[@class='nav-item nav-link'])[1]",
    clickonsaveBtn2: "(//button[text()='Save'])[1]",
    groupSearchInpBx:"//input[@class='form-control']",
    searchBtn:"//button[@class='btn btn-primary']",
    verifyGroupName:"(//td[@class='vuetable-slot']/descendant::span)[1]",
    clickGroupEditBt:"(//i[@class='fas fa-pen-square fa-lg fa-fw'])[1]",
    groupInputName: "//input[@id='name']",
    groupTextAreaDescription: "//textarea[@id='description']",
    groupEllipsis: "//div[@id='main']//tbody//button[@aria-haspopup='menu']",
    groupDelete: '//span[text()="Delete Group"]',
    loadingGroup: '.jumbotron.jumbotron-fluid',
    searchGroup: '[placeholder="Search"]',
    groupPagination: ".pagination",
    confirmButtonGroup: '//button[text()="Confirm"]',

    //File Manager
    addPublicFileBtn: '[aria-label="Upload Public File"]',
    selectFileBtn: '[data-cy="file-upload-button"]',
    doneBtn: '[class="btn btn-primary"]',

    //CRUD Notification:
    createNotificationsPermission: '[for="permission_create-notifications"]',
    deleteNotificationPermission: '[for="permission_delete-notifications"]',
    editNotificationPermission: '[for="permission_edit-notifications"]',
    viewNotificationPermission: '[for="permission_view-notifications"]',
    //CRUD Comments:
    createCommentsPermission: '[for="permission_create-comments"]',
    deleteCommentsPermission: '[for="permission_delete-comments"]',
    editCommentsPermission: '[for="permission_edit-comments"]',
    viewCommentsPermission: '[for="permission_view-comments"]',
    //UsernameAndPassword
    editUserAndPasswordPermission:'[for="permission_edit-user-and-password"]',
    //CRUD Users:
    createUsersPermission: '[for="permission_create-users"]',
    deleteUsersPermission: '[for="permission_delete-users"]',
    editPersonalProfilePermission: '[for="permission_edit-personal-profile"]',
    editUsersPermission: '[for="permission_edit-users"]',
    viewOtherUsersProfilePermission: '[for="permission_view-other-users-profiles"]',
    viewUsersPermission: '[for="permission_view-users"]',
    //CRUD Processes:
    createProcessesPermission: '[for="permission_create-processes"]',
    editProcessesPermission: '[for="permission_edit-processes"]',
    viewProcessesPermission: '[for="permission_view-processes"]',
    
    //Authentication Client
    authClientButton: '//button[@aria-label="Create Auth Client"]',
    AuthName: '//input[@id="name"]',
    AuthGrant:'//input[@value="authorization_code_grant"]',
    redirect:'//input[@id="redirect"]',
    searchAuth: '//input[@aria-label="Search"]',
    OneAuthInList: '1 - 1 of 1 Auth Client',
    buttonSaveAuth: '//button[text()="Save"]',
    ellipsisMenu: '//button/i[@class="fas fa-ellipsis-h ellipsis-menu-icon"]',
    popMenuAuth: '(//button[@aria-haspopup="menu"]/i)[2]',
    editMenuAuth: '//div/span[text()="Edit Auth Client"]',
    deleteMenuAuth: '//div/span[text()="Delete Auth Client"]',
    confirmAuth: '//button[text()="Confirm"]',
    ellipsisAuth: "//div[@id='main']//tbody//button[@aria-haspopup='menu']",

    //Settings
    settigns_leftMenu: "[id='menu']",
    settigns_optionMenu: '//*[@id="menu"]//*[contains(@class,"list-item")][contains(text(),"optionMenu")]',
    settigns_optionCategory: '//*[@id="menu"]//*[contains(@class,"menu-header")]/span[contains(text(),"optionCategory")]',
    settigns_search: '[aria-label="Advanced Search (PMQL)"]',
    settigns_tbody: '//*[@id="settings"]//table//tbody//tr[1]',
    settigns_closeSearch: '.settings-listing>* .search-bar-container > .fa-times',
    deleteEmail: '//button[contains(@icon,"fa-trash")]',
    emailMenuSettings: '//div/span[contains(text(),"Email")]',
    actionsbyEmailSettings: '//div/div[contains(text(),"Actions By Email")]',
    emailDefaultSettings: '//div/div[contains(text(),"Email Default Settings")]',
    connectorAndAddEmailServer: '//div/button[@data-cy="EMAIL_CONNECTOR_ADD_MAIL_SERVER"]',
    logInAuth: '//div/span[contains(text(),"Log-In & Auth")]',
    ldap: '//div/div[contains(text(),"LDAP")]',
    logInOptions: '//div/div[contains(text(),"Log-In Options")]',
    scim: '//div/div[contains(text(),"SCIM")]',
    sessionControl: '//div/div[contains(text(),"Session Control")]',
    sso: '(//div/div[contains(text(),"SSO")])[1]',
    userSettings: '//div/span[contains(text(),"User Settings")]',
    userSignals: '//div/div[contains(text(),"User Signals")]',
    users: '//div/div[contains(text(),"Users")]',
    integrations: '//div/span[contains(text(),"Integrations")]',
    docusign: '//div/div[contains(text(),"DocuSign")]',
    externalIntegrations: '//div/div[contains(text(),"External Integrations")]',
    idp: '//div/div[contains(text(),"IDP")]'
}