export default{
    customLoginLogo: '//input[@id="custom-login-logo"]',
    customLogo: '//input[@id="custom-logo"]',
    customIcon: '//input[@id="custom-icon"]',
    customFavicon: '//input[@id="custom-favicon"]',
    altText: '//input[@id="alt-text"]',
    primary: '//label[text()="Primary"]/ancestor::div/button',
    colorD0021B:'//div[@role="group"]/div[@aria-label="Color:#D0021B"]',
    secondary: '//label[text()="Secondary"]/ancestor::div/button',
    colorF5A623:'//div[@role="group"]/div[@aria-label="Color:#F5A623"]',
    success: '//label[text()="Success"]/ancestor::div/button',
    colorF8E71C: '//div[@role="group"]/div[@aria-label="Color:#F8E71C"]',
    info: '//label[text()="Info"]/ancestor::div/button',
    color8B572A:'//div[@role="group"]/div[@aria-label="Color:#8B572A"]',
    warning: '//label[text()="Warning"]/ancestor::div/button',
    color7ED321: '//div[@role="group"]/div[@aria-label="Color:#7ED321"]',
    danger: '//label[text()="Danger"]/ancestor::div/button',
    color417505: '//div[@role="group"]/div[@aria-label="Color:#417505"]',
    dark: '//label[text()="Dark"]/ancestor::div/button',
    colorBD10E0:'//div[@role="group"]/div[@aria-label="Color:#BD10E0"]',
    light: '//label[text()="Light"]/ancestor::div/button',
    color9013FE: '//div[@role="group"]/div[@aria-label="Color:#9013FE"]',
    multiselect: '//div[@class="multiselect__select"]',
    monoType: '//li[@id="option-0-1"]/span[@class="multiselect__option"]/span[text()="Mono Type"]',
    buttonSecondary: '//button[@class="btn ml-3 btn-secondary"]',
    resetButton: '//button[contains(text(),"Reset")]',
    confirmButton: '//button[contains(text(),"Confirm")]',
    saveButton: '//button[contains(text(),"Save")]',
    taskSelectList: '//div[@class="multiselect__tags"]',
    taskSelectListOption: "(//li[@class='multiselect__element']//span)[1]",
    taskInput: '//input[@data-cy="screen-field-form_input_1"]',
    taskTextArea: '//textarea[@data-cy="screen-field-form_text_area_1"]',
    taskSignature: '//div[@data-cy="screen-field-sig1"]//canvas',
    newSubmitButton: '//button[contains(text(),"New Submit")]',
    taskInputValidationText: '//div[@class="invalid-feedback"]',
    customizeMain: '//div[@id="main"]',
    customFontInput: '//input[@id="custom-font"]',
    loadingCSS: '[id="modalLoading"]'
}