export default {
    addDataConnector: '[aria-label="Create Data Connector"]',
    nameInput: '#title',
    descriptionInput: '#description', 
    authenticatonDropdownXpath: '(//div[@aria-label="Authentication Method"]/div)[1]',
    connectorTypeDropdownXpath: '(//div[@aria-label="Connector type"]/div)[1]',
    authenticatonDropdown: '[aria-label="Authentication Type"]',
    authenticationTypeInput: '[name="Authentication Method"]',
    connectorTypeInput: '[name="type"]',
    authType: '//span[text()="AuthType"]',
    connectorType: '//span[text()="connectorType"]',
    saveBtn: "(//button[normalize-space()='Save'])[1]",
    configurationtab: '(//li[@role="presentation"])[1]',
    tokenInput: '#token',
    addResource: '[aria-label="Create Resource"]',
    addResourceWithBearerToken: '//button[@aria-label="Create Resource"]',
    resourceDescription: '[name="description"]',
    resourceMethod: '[name="method"]',
    resourceURL: '[name="url"]',
    addBtn: '//button[text()="add"]',
    resourcestab: '(//li[@role="presentation"])[2]',
    resourceSendBtn:"//button[text()='Send']",
    configBtn:"(//a[@role='tab'])[2]",
    tokenTxtBx:'[id="token"]',
    resourcenavBtn:"(//a[@role='tab'])[1]",
    resourceNmeTxt:'[name="purpose"]',
    CategoryTxt: '[class="multiselect__tag"] span',
    dataSourceIndex: '//div[@id="dataSourceIndex"]//div[@id="search"]//input',
    dataSourceIndexLoading: '//div[@id="dataSourceIndex"]//div[@class="jumbotron jumbotron-fluid"]//h3',
    dataSourceEllipsis: '//*[@id="dataSourceIndex"]/div[2]/div[2]/table/tbody/tr/td[7]/div/button',
    dataSourceEditButtonForSpecificUser: '//*[@id="dataSourceIndex"]/div[2]/div[2]/table/tbody/tr/td[7]/div/ul/div/li[1]/a',
    dataSourceRemoveButtonForSpecificUser: '//*[@id="dataSourceIndex"]/div[2]/div[2]/table/tbody/tr/td[7]/div/ul/div/li[4]/a',
    inputName: '//input[@id="name"]',
    inputDescription: '//textarea[@id="description"]',
    OneDataConnectorInList: '//div[text()="1 - 1 of 1 Data Connector"]',
    confirmButtonDelete: '//button[text()="Confirm"]',
    resourcesTitle: '//li/a[text()="Resources"]',
    noDataAvailable: '//h3[text()="No Data Available"]',
    textareaDescription: '//textarea[@placeholder="Enter description"]',
    inputURL: '//input[@placeholder="Enter a full API URL"]',
    firstRowDataConnector: '//div[@id="dataSourceIndex"]//tbody/tr',
    addProjectModel: '//div[@class="modal-body"]',
    searchInputBoxDC:"//div[@id='dataSourceIndex']//*[@id='search-box']",
    threePointsBtnXpathDC: '//div[@id="main"]//div[@id="dataSourceIndex"]//tbody//button[@aria-haspopup="menu"]',
    loadingSpinnerDC:"#dataSourceIndex > div.container-fluid > div > div.jumbotron.jumbotron-fluid",
    resourcesMenu: '//a[text()="Resources"]',
    optionBtn: '[id="dataSourceIndex"] button[aria-haspopup="menu"]',
    modalOptions: '[class="dropdown-menu show"] span',
    selectOptionModal: '//ul[@class="dropdown-menu show"]//span[text()="modalOption"]',
    resourceNameDC: '[role="tabpanel"] [name="purpose"]',
    resourceDescriptionDC: '[role="tabpanel"] [placeholder="Enter description"]',
    resourceTimeoutDC: "//legend[text()='Timeout']/following-sibling::div//input[@type='number']",
    resourceRetryAttemptsDC: "//legend[text()='Retry Attempts']/following-sibling::div//input[@type='number']",
    resourceRetryWaitTimeDC: "//legend[text()='Retry Wait Time']/following-sibling::div//input[@type='number']",
    resourceSaveBtnDC: '//div[@class="card-body"]//button[contains(text(),"Save")]',
}
