export default {
    
    threePointsBtnXpathScreen:'//div[@id="screenIndex"]//table/tbody/tr//button[@aria-haspopup="menu"]',
    searchInputScreen:'[data-cy="input-search"]',
    addScreenTemplateModel: '//div[@class="modal-body"]',
    userPermissionsScreen:'//*[@class="btn btn-link d-flex w-100 justify-content-between"]',
    nameScreenTemplate: '[name="name"]',
    descriptionScreentemplate:'//textarea[@name = "description"]',
    versionScreenTemplate: '[name="version"]',
    makePublickScreentemplate: '//label[contains(text(),"Make Public")]',
    screenTemplateCategory:'//div[@class="modal-body"]//div[@name="category"]',
    saveCreateScreenTemplate:'//button[contains(text(),"Save")][1]',
    screenTableBx:'[data-cy="screens-table"]',
    screenIndex: '[id="screenIndex"]',
    screenPublicTemplate:'[id="publicTemplatesIndex"]',
    screenMyTemplate:'[id="myTemplatesIndex"]',
    noDataAvailable: '[class="vuetable-empty-result"]',
    searchScreen:'[data-cy="input-search"]',
    loadingSpinnerScreen:'(//div[".icon-container"]/h3[contains(text(),"Loading")])[1]',
    tabMyTemplates:'//*[@id="nav-myTemplates-tab"]',
    tableScreenTemplate:'[data-cy="my-templates-table"]',
    screenTemplateList:'[id="myTemplatesIndex"]',
    searchInputScreenTemplate: '//div[@id="myTemplatesIndex"]//textarea[@placeholder="Search here"]',
    menuOptionScreenTemplateMyTemplate2:'//div[@id="myTemplatesIndex"]//table/tbody/tr//button[@aria-haspopup="menu"]',
    menuOptionScreenTemplateMyTemplate:'//div[@id="myTemplatesIndex"]//button[@aria-haspopup="menu"]',
    menuOptionScreenTemplatePublic2:'//div[@id="publicTemplatesIndex"]//table/tbody/tr//button[@aria-haspopup="menu"]',
    menuOptionScreenTemplatePublic:'//div[@id="publicTemplatesIndex"]//button[@aria-haspopup="menu"]',
    searchInputScreenTemplatePublic:'//div[@id="publicTemplatesIndex"]//textarea[@aria-label="Search"]',
    confirmDeleteScreentemplate:'//button[text()="Confirm"]',
    downloadExport:'//*[@class="btn btn-secondary ml-2"]',
    ImportButtonMyTemplate:'(//*[@id="import_template"])[1]',
    titleImportScreenTemplate:'(//div[@id="importScreen"]//h5)[1]',
    browseScreenTemplate: '[data-cy="button-browse"]',
    importBtnScreentemplate:'//*[@class="btn btn-primary ml-2"]',
    importBtnScreenMyTemplate: '[data-cy="button-import"]',
    loadingScreenTemplateSpinner:'[class="fas fa-circle-notch fa-spin"]',
    screenTemplateTableBx:'[data-cy="my-templates-table"]',
    screentemplateIndex:'[id="nav-myTemplates"]',
    totalPaginationScreenMyTemplate:'[data-cy="my-templates-pagination"] span[class="pagination-total"]',

    
}