export default{
    detailsTab: '//button[contains(text(),"Details")]',
    commentsTab: '//button[contains(text(),"Comments")]',
    collapseButton: '[data-toggle="collapse"]',
    reassignButton: '//button[contains(text(),"Reassign")]', 
    cancelRequest: '//button[contains(text(),"Cancel Request")]',
    inProgress: '//span[text()="In Progress"]',
    participants: '//p[contains(text(),"Participants")]',
    inProgressSince: '//p[contains(text(),"In Progress Since:")]',
    requestedBy: '//p[contains(text(),"Requested By:")]',
    adminUserIcon: '//span/span[contains(text(),"AU")]',
    openLabel: '//span[text()="open"]',
    dueIn: '//p[contains(text(),"Due in 3 days")]',
    autoSave: '//span[contains(text(),"AUTOSAVE")]',
    assignedTo: '//p[contains(text(),"Assigned To:")]',
    escalateManagerButton: '//button[contains(text(),"Escalate to Manager")]',
    requestTitle: '//p[contains(text(),"Request")]',
    completed: '//span[text()="Completed"]',
    addComment: '//textarea[@placeholder="Add a comment..."]',
    comment: '(//button[contains(text(),"Comment")])[2]',
    commentDetails: '//*[@clip-path="url(#clip0_1212_264229)"]',
    edit: '//*[@clip-path="url(#clip0_1212_264225)"]',
    editTitle: '//button[contains(text(),"Edit")]',
    delete: '//*[@clip-path="url(#clip0_1212_264227)"]',
    confirmButton: '//button[contains(text(),"Confirm")]',
    taskCollapsibleBtn: '//button[contains(text(),"option")]'
}