export default {
    avatar: '[id="avatarMenu"]',
    assetsProcesses: '//p[contains(text(),"Processes")]',
    assetsScreens: '//p[contains(text(),"Screens")]',
    assetsScripts: '//p[contains(text(),"Scripts")]',
    assetsDecisionTables: '//p[contains(text(),"Decision Tables")]',
    assetsDataConnectors: '//p[contains(text(),"Data Connectors")]',
    myTasks: '//p[contains(text(),"My Tasks")]',
    tasks: '//th[contains(text(),"Task")]',
    requests: '//th[contains(text(),"Request")]',
    due:'//th[contains(text(),"Due")]',
    menuTaskExpansion: '(//div/a[@href="#"]/i)[1]',
    searchTask: '(//button/i[@class="fas fa-search"])[1]',
    inputTask: '//div/div/input[@class="form-control narrow-input"]',
    eyeHardcoded: '(//a[contains(text(),"A")]/ancestor::tr/td/span/i[@class="fa fa-eye"])[1]',
    myRequests: '//p[contains(text(),"My Requests")]',
    numberRequest: '//th[contains(text(),"#")]',
    nameRequest: '//th[contains(text(),"Name")]',
    statusRequest: '//th[contains(text(),"Status")]',
    searchRequest: '(//button/i[@class="fas fa-search"])[2]',
    inputRequest: '//div/div/input[@class="form-control narrow-input"]',
    hrefRequestHarcoded: "//span[contains(text(),'processName')]/ancestor::tr/td/div/div/a",
    menuRequestExpansion: '(//div/a[@href="#"]/i)[2]',
    searchRequestProcess: '(//button/i[@class="fas fa-search"])[3]',
    inputProcess: '//div/div/input[@class="form-control narrow-input"]',
    processFoundHarcodedStartFound: "//span[contains(text(),'process')]/ancestor::div[@class='d-flex justify-content-between']/div/button[contains(text(),'Start')]",
    importProjectButtonList: '//button[@aria-label="Import Project"]',
    loadingSpinnerProject: "(//div['.icon-container']/h3[contains(text(),'Loading')])[1]",
    projectList: "//tbody['.vuetable-body']/tr",
    optionButtonDesigner: "//button['.btn custom-button mb-2 btn-secondary btn-sm btn-block']/p[contains(text(),'option')]",
    assetVerification: "//td/a[contains(text(),'asset')]"
 };